<div class="bg-gray-100 w-screen h-screen flex items-center justify-center">
    <?php
    if (!isset($data)) {
    ?>
        <form action="#" method="post" class="flex flex-col text-gray-800 capitalize">
            <label for="logo" class="text-6xl text-center p-3">
                <ion-icon name="at-circle-outline"></ion-icon>
            </label>
            <label for="name" class="m-2">
                <input type="text" name="name" id="name" class="bg-transparent border-2 shadow-lg" placeholder="enter name" required>
            </label>
            <label for="email" class="m-2">
                <input type="email" name="email" id="email" class="bg-transparent border-2 shadow-lg" placeholder="enter email" required>
            </label>
            <label for="password" class="m-2">
                <input type="password" name="password" id="password" class="bg-transparent border-2 shadow-lg" placeholder="enter password" required>
            </label>
            <label for="role" class="m-2">
                <input type="text" name="role" id="role" class="bg-transparent border-2 shadow-lg" placeholder="enter role" required>
            </label>
            <label for="btn" class="m-2">
                <input type="submit" value="register" id="btn" class="bg-indigo-500 w-full p-2.5 text-white cursor-pointer hover:bg-indigo-700 shadow-lg" placeholder="enter email" required>
            </label>
        </form>
    <?php
    }
    ?>
    <?php
    if (isset($data)) {
    ?>
        <div class="bg-gray-300 m-3 max-w-sm break-all text-gray-700 p-3 rounded-lg shadow-inner">
            <p><?php echo $data; ?></p>
        </div>

        <div class="noti fixed bottom-0 m-3 right-0 bg-indigo-500 p-3 text-gray-200 rounded-lg shadow-lg">
            <p>Please Save this token.</p>
        </div>
    <?php
    }
    ?>
</div>